# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-07 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('deviceNumber', models.IntegerField()),
            ],
        ),
    ]
